[CRB-206] Process requests concurrently
gluwa/Creditcoin-Gateway pull request #7
Opened 2021-10-19 23:13 UTC by nathanwhit

Currently, only one request can be handled at a time which negatively impacts both throughput and latency. This PR makes it so gateway requests can be handled concurrently. This improves overall performance and makes the gateway's performance more predictable, as slow RPC calls no longer block other requests from being processed.

The performance results (as tested using the procedure described in the load testing documentation) running locally on my machine are:

**Parallel benchmark (with 16 cores):**
Before PR - 8.16 req/sec
With PR   - 105.68 req/sec

**Sequential benchmark:**
Before PR - 8.28 req/sec
With PR   - 8.35 req/sec

In order to make the plugins asynchronous, the plugin interface (defined in `ccplugin`) needed changes. Instead of trying to coordinate two simultaneous PRs, I added a local package (`CCGatewayPlugin`) that defines an asynchronous version of the plugin interface. This can be changed, if desired.

2021-10-20 00:35 UTC, seandeneen-gluwa requested changes

2021-10-20 00:35 UTC, seandeneen-gluwa commented on ccgateway/plugins/bitcoin/Bitcoin.cs
>                  var transactionInfoResponse = rpcClient.GetRawTransactionInfo(transactionId);
`await rpcClient.GetRawTransactionInfoAsync` might work better here if we make this into an async method.

2021-10-20 10:47 UTC, atodorov requested changes
Docker images fail to build - some changes requested.

2021-10-20 10:47 UTC, atodorov commented on CCGatewayPlugin/CCGatewayPlugin.csproj
> +</Project>
See GitHub Actions log. Docker image can't find this file to build ccgateway.

2021-10-20 10:47 UTC, atodorov commented on ccgateway/Program.cs
> +                var pluginConfig = config.GetSection(action);
Suggestion: you can move L53 and L56 inside the else block on L61 b/c they aren't needed outside of it (shaving off a few microseconds probably).

2021-10-21 01:16 UTC, ghost commented
@nathanwhit LMK when you plan to merge this, because https://dev.azure.com/gluwa/Gluwa/_build?definitionId=128 will need to be updated to match the new folder structure.

2021-10-21 10:50 UTC, atodorov approved these changes

2021-10-21 23:27 UTC, seandeneen-gluwa approved these changes

2021-10-26 14:49 UTC, CAGS295 approved these changes

2021-10-27 17:39 UTC, merged